#!/usr/bin/env ruby

cmd = ARGV.shift

path = `which #{cmd}`.chomp

mode = ENV['STACKPROF_MODE']&.to_sym || :cpu
out = ENV['STACKPROF_OUT'] || 'stackprof-out'

require 'stackprof'
ex = nil
StackProf.run(mode: mode, out: out) do
  begin
    load path
  rescue Exception => ex
  end
end

raise ex if ex
