#!/usr/bin/env ruby

require 'optparse'
require 'stackprof'

opt = OptionParser.new

mode = ENV['STACKPROF_MODE']&.to_sym || :cpu
out = ENV['STACKPROF_OUT'] || 'stackprof-out'

opt.on('-m MODE', '--mode=MODE'){|v| mode = v.to_sym}
opt.on('-o FILE', '--out=FILE'){|v| out = v}

opt.order!(ARGV)

cmd = ARGV.shift
unless cmd
  puts opt.help
  exit 1
end

path = `which #{cmd}`.chomp

$PROGRAM_NAME = cmd

ex = nil
StackProf.run(mode: mode, out: out) do
  begin
    load path
  rescue Exception => ex
  end
end

raise ex if ex
